apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-sc-provisioner
  labels:
    app: nfs-sc-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-sc-provisioner
  template:
    metadata:
      labels:
        app: nfs-sc-provisioner
    spec:
      serviceAccountName: nfs-sc-provisioner
      containers:
        - name: nfs-sc-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-sc-provisioner
            - name: NFS_SERVER
              value: 172.31.0.100
            - name: NFS_PATH
              value: /myshare
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.31.0.100
            path: /myshare
