apiVersion: v1
kind: Service
metadata:
  name: blue-green-svc
spec:
  ports:
  - port: 31005
    nodePort: 31001
    targetPort: node-port
    protocol: TCP
  selector:
    app: green
  type: NodePort
