apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: web
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None  # Headless service, no load balancing
  selector:
    app: web

