# Primary Chart Details
apiVersion: v2
name: my-tiny-web
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: 1.16.0


# Add Dependencies here 
dependencies:
  - name: nginx
    version: 13.2.12 
    repository: "https://marketplace.azurecr.io/helm/v1/repo"


